### ISSUE TITLE
How do you generate the smart-app-banner.js file?

### ISSUE THREAD

**Issue by confile** [kudago/smart-app-banner#29]
Could you please explain how you generate the smart-app-banner.js file?

**Comment by dy** [comment]
Hi! We generate the file via browserify by:

``` sh
npm run build
```

You can see the actual command being executed in [package.json](https://github.com/kudago/smart-app-banner/blob/master/package.json#L7).

In that, if you want your own custom build of smartbanner, e. g. for debug purposes, you can run `browserify index.js -d -o smartbanner.js`.

**Comment by drmichaelgorski** [comment]
@dfcreative `npm run build` leads to the following error: 

```
Error: Cannot find module 'component-query' from '/Users/mg/Downloads/smart-app-banner'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.10.28
npm ERR! npm  v2.14.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! smart-app-banner@1.1.3 build: `browserify index.js -s SmartBanner | ccjs - > smart-app-banner.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the smart-app-banner@1.1.3 build script 'browserify index.js -s SmartBanner | ccjs - > smart-app-banner.js'.
npm ERR! This is most likely a problem with the smart-app-banner package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify index.js -s SmartBanner | ccjs - > smart-app-banner.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls smart-app-banner
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mg/Downloads/smart-app-banner/npm-debug.log

```

What went wrong here?

**Comment by drmichaelgorski** [comment]
Using `browserify index.js -d -o smartbanner.js` I get: 

```
Error: Cannot find module 'component-query' from '/Users/mg/Downloads/smart-app-banner'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

**Comment by dy** [comment]
Yes, you have to install all the dependencies first: _npm install_. I'll update readme.

**Comment by drmichaelgorski** [comment]
Thanks that works.

**Comment by drmichaelgorski** [comment]
@dfcreative Thanks a lot I made a pull request here: https://github.com/kudago/smart-app-banner/pull/30
